name: Check Checklist Issue on PR

on:
  pull_request:
    branches:
      - develop

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub CLI
        run: echo ${{ secrets.API_TOKEN }} | gh auth login --with-token

      - name: Check if Checklist Issue is Completed
        id: check-issue
        run: |
          ISSUES=$(gh issue list --label "question" --state open --json title,body)
          echo "ISSUES=$ISSUES" >> $GITHUB_ENV
          CHECKLIST_COMPLETED=true
          for row in $(echo "${ISSUES}" | jq -r '.[] | @base64'); do
            _jq() {
             echo ${row} | base64 --decode | jq -r ${1}
            }
            TITLE=$(_jq '.title')
            BODY=$(_jq '.body')
            if [[ "$TITLE" == "Code Review Checklist" ]]; then
              CHECKLIST_COMPLETED=false
              for ITEM in $(echo "$BODY" | grep -o '\[ \]'); do
                if [[ "$ITEM" == "[ ]" ]]; then
                  CHECKLIST_COMPLETED=false
                  break
                fi
              done
              if $CHECKLIST_COMPLETED; then
                break
              fi
            fi
          done

          echo "CHECKLIST_COMPLETED=$CHECKLIST_COMPLETED" >> $GITHUB_ENV

      - name: Fail if Checklist is not Completed
        run: |
          if [ "$CHECKLIST_COMPLETED" = "false" ]; then
            echo "Checklist is not completed. Please complete the checklist before merging."
            exit 1
          else
            echo "Checklist is completed."
          fi
