name: Check Checklist Issue on PR

on:
  pull_request:
    branches:
      - develop

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find related issue
        id: find-issue
        uses: actions/github-script@v6
        with:
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'question',
              state: 'open'
            });
            if (issues.length === 0) {
              core.setFailed('No open checklist issue found.');
            } else {
              core.setOutput('issue_number', issues[0].number);
            }

      - name: Check if issue is complete
        if: success()
        id: check-issue
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = core.getInput('issue_number');
            const { data: issue } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number
            });
            const checklistComplete = issue.body.split('\n').every(line => !line.startsWith('- [ ]'));
            if (!checklistComplete) {
              core.setFailed('Checklist issue is not fully completed.');
            }

      - name: Approve PR if checklist is complete
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });
