name: Check Checklist Issue on PR

on:
  pull_request:
    branches:
      - develop

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate GitHub CLI
        run: echo ${{ secrets.API_TOKEN }} | gh auth login --with-token

      - name: Get Checklist Issue
        id: get-issue
        run: |
          ISSUES=$(gh issue list --label "checklist" --state open --json number)
          echo "ISSUES=$ISSUES" >> $GITHUB_ENV
          ISSUE_NUMBER=$(echo "$ISSUES" | jq -r '.[0].number')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Check if Checklist Issue is Completed
        id: check-issue
        run: |
          ISSUE_BODY=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }} | jq -r '.body')
          
          CHECKLIST_COMPLETED=true
          if echo "$ISSUE_BODY" | grep -q '\[ \]'; then
            CHECKLIST_COMPLETED=false
          fi

          echo "CHECKLIST_COMPLETED=$CHECKLIST_COMPLETED" >> $GITHUB_ENV

      - name: Fail if Checklist is not Completed
        run: |
          if [ "$CHECKLIST_COMPLETED" = "false" ]; then
            echo "Checklist is not completed. Please complete the checklist before merging."
            exit 1
          else
            echo "Checklist is completed."
          fi
