name: Create Checklist Issue on Push

on:
  push:
    branches:
      - feature**

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Code Review Checklist"
          content-filepath: .github/ISSUE_TEMPLATE/checklist.md
          labels: checklist