name: Create Issue with Checklist

on:
  pull_request:
    types: [opened]

jobs:
  check-issue:
    needs: create-issue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if checklist is completed
        run: |
          ISSUE_NUMBER=$(echo "${{ needs.create-issue.outputs.issue_number }}")
          RESPONSE=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER)
          CHECKLIST=$(echo $RESPONSE | jq '.body')

          INCOMPLETE_ITEMS=$(echo "$CHECKLIST" | grep -o '\- \[ \]')

          if [ -n "$INCOMPLETE_ITEMS" ]; then
            echo "Checklist not completed."
            exit 1
          else
            echo "Checklist completed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
