name: Create Checklist Issue on Push

on:
  push:
    branches:
      - feature/*

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read Checklist Template
        id: read-template
        run: |
          CHECKLIST=$(cat .github/ISSUE_TEMPLATE/checklist.md)
          echo "::set-output name=checklist::$CHECKLIST"

      - name: Create Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueTitle = "Code Review Checklist";
            const issueBody = process.env.CHECKLIST;
            const labels = ["checklist"];
            const { data: issue } = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: labels
            });
            core.info(`Issue created: ${issue.html_url}`);
        env:
          CHECKLIST: ${{ steps.read-template.outputs.checklist }}
