name: Create Checklist Issue on Push

on:
  push:
    branches:
      - feature/*

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read Checklist Template
        id: read-template
        run: |
          CHECKLIST=$(cat .github/ISSUE_TEMPLATE/checklist.md | jq -sR .)
          echo "CHECKLIST=$CHECKLIST" >> $GITHUB_ENV

      - name: Create Issue using REST API
        run: |
          echo ${{ github.repository}}
          curl -L \
            -X POST \
            -H "Authorization: Bearer ${{secrets.API_TOKEN}}" \
            -H "Accept: application/vnd.github.full+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{github.repository}}/issues \
            -d '{"title":"Code Review Checklist","body": '"$CHECKLIST'","labels":["question"]}'
        env:
          CHECKLIST: ${{ env.CHECKLIST }}
